In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

In [3]:
customers = pd.read_csv(r"C:\Users\navee\Music\nakul nagar document\chrome download\connection data\Cusmtomer_data.csv")
cards = pd.read_csv(r"C:\Users\navee\Music\nakul nagar document\chrome download\connection data\Cards_Data.csv")
merchants = pd.read_csv(r"C:\Users\navee\Music\nakul nagar document\chrome download\connection data\merchant_table.csv")
transactions = pd.read_csv(r"C:\Users\navee\Music\nakul nagar document\chrome download\connection data\Transaction_Data_250k.csv")

In [ ]:
customers.head()
cards.head()
merchants.head()
transactions.head()

,Transaction_ID,Customer_ID,Card_ID,Merchant_ID,Transaction_Date,Transaction_Time,Transaction_Amount,Payment_Method,Transaction_Channel,Device_Type,Transaction_Status,Is_International,Fraud_Flag,Fraud_Reason,Merchant_Risk_Level,Merchant_Category,Customer_State,Customer_City,Merchant_State,Merchant_City
0,TXN1000001,CUST100660,CARD500875,MER100380,2024-03-03,05:50:10,21748.02,Debit Card,Mobile App,Android Mobile,Successful,1,0,NaN,Low,Hotel,Tamil Nadu,Madurai,Tamil Nadu,Salem
1,TXN1000002,CUST111388,CARD514772,MER100017,2023-11-08,06:55:15,9960.60,Debit Card,POS,POS Terminal,Successful,0,0,NaN,Low,Travel,Kerala,Kollam,Haryana,Nuh
2,TXN1000003,CUST115872,CARD520625,MER100143,2023-01-11,02:17:28,838.61,Debit Card,ATM,ATM Machine,Successful,0,0,NaN,Low,Food Delivery,Uttar Pradesh,Agra,West Bengal,Kolkata
3,TXN1000004,CUST109049,CARD511773,MER100053,2023-05-25,01:48:56,52694.99,Credit Card,POS,POS Terminal,Successful,0,0,NaN,Low,Financial Services,Punjab,Ludhiana,Madhya Pradesh,Indore
4,TXN1000005,CUST114459,CARD518771,MER100064,2023-10-22,00:23:32,1043.40,Debit Card,Online Web,Android Mobile,Successful,0,0,NaN,Low,Entertainment,Maharashtra,Thane,Madhya Pradesh,Jabalpur

In [16]:
cards.head()

,Card_ID,Customer_ID,Card_Type,Card_Network,Credit_Limit,Card_Status,Contactless,Card_Mode,Issue_Date,Expiry_Date
0,CARD500001,CUST100001,Gold,RuPay,587317,Active,Yes,Physical,2021-04-24,2026-04-24
1,CARD500002,CUST100002,Silver,Visa,150720,Active,Yes,Virtual,2020-06-30,2025-06-30
2,CARD500003,CUST100003,Gold,RuPay,631005,Active,Yes,Physical,2022-04-04,2027-04-04
3,CARD500004,CUST100004,Silver,Mastercard,285015,Expired,Yes,Virtual,2020-07-21,2025-07-21
4,CARD500005,CUST100005,Gold,Mastercard,348591,Active,Yes,Physical,2024-07-24,2029-07-24

In [17]:
merchants.head()

,Merchant_ID,Merchant_Name,Merchant_Category,State,City,Merchant_Risk_Level,Merchant_Rating,Merchant_Status,Merchant_Since
0,MER100001,Paytm Utilities,Utilities,Haryana,Gurugram,Medium,4.8,Active,2012-07-29
1,MER100002,Coursera,Education,Bihar,Patna,Low,4.3,Active,2008-03-09
2,MER100003,Redbus,Travel,Bihar,Muzaffarpur,Low,4.7,Active,2006-08-12
3,MER100004,Air India,Airline,Tamil Nadu,Salem,Low,3.6,Active,2008-03-30
4,MER100005,IndiGo,Airline,Punjab,Jalandhar,Medium,4.1,Active,2007-07-18

In [18]:
transactions.head()

,Transaction_ID,Customer_ID,Card_ID,Merchant_ID,Transaction_Date,Transaction_Time,Transaction_Amount,Payment_Method,Transaction_Channel,Device_Type,Transaction_Status,Is_International,Fraud_Flag,Fraud_Reason,Merchant_Risk_Level,Merchant_Category,Customer_State,Customer_City,Merchant_State,Merchant_City
0,TXN1000001,CUST100660,CARD500875,MER100380,2024-03-03,05:50:10,21748.02,Debit Card,Mobile App,Android Mobile,Successful,1,0,NaN,Low,Hotel,Tamil Nadu,Madurai,Tamil Nadu,Salem
1,TXN1000002,CUST111388,CARD514772,MER100017,2023-11-08,06:55:15,9960.60,Debit Card,POS,POS Terminal,Successful,0,0,NaN,Low,Travel,Kerala,Kollam,Haryana,Nuh
2,TXN1000003,CUST115872,CARD520625,MER100143,2023-01-11,02:17:28,838.61,Debit Card,ATM,ATM Machine,Successful,0,0,NaN,Low,Food Delivery,Uttar Pradesh,Agra,West Bengal,Kolkata
3,TXN1000004,CUST109049,CARD511773,MER100053,2023-05-25,01:48:56,52694.99,Credit Card,POS,POS Terminal,Successful,0,0,NaN,Low,Financial Services,Punjab,Ludhiana,Madhya Pradesh,Indore
4,TXN1000005,CUST114459,CARD518771,MER100064,2023-10-22,00:23:32,1043.40,Debit Card,Online Web,Android Mobile,Successful,0,0,NaN,Low,Entertainment,Maharashtra,Thane,Madhya Pradesh,Jabalpur

In [19]:
print("customers",customers.shape)
print("cards",cards.shape)
print("merchants" ,merchants.shape)
print("transactions",transactions.shape)

customers (25000, 12)
cards (32457, 10)
merchants (500, 9)
transactions (250000, 20)

In [23]:
print("customers null values:",customers.isnull().sum())
print("cards null values:",cards.isnull().sum())
print("merchants null values:",merchants.isnull().sum())
print("transactions null values:",transactions.isnull().sum())

customers null values: Customer_ID         0
Customer_Name       0
Gender              0
Age                 0
Marital_Status      0
Occupation          0
Annual_Income       0
Customer_Segment    0
State               0
City                0
Account_Type        0
Customer_Since      0
dtype: int64
cards null values: Card_ID         0
Customer_ID     0
Card_Type       0
Card_Network    0
Credit_Limit    0
Card_Status     0
Contactless     0
Card_Mode       0
Issue_Date      0
Expiry_Date     0
dtype: int64
merchants null values: Merchant_ID            0
Merchant_Name          0
Merchant_Category      0
State                  0
City                   0
Merchant_Risk_Level    0
Merchant_Rating        0
Merchant_Status        0
Merchant_Since         0
dtype: int64
transactions null values: Transaction_ID              0
Customer_ID                 0
Card_ID                     0
Merchant_ID                 0
Transaction_Date            0
Transaction_Time            0
Transaction_Amount          0
Payment_Method              0
Transaction_Channel         0
Device_Type                 0
Transaction_Status          0
Is_International            0
Fraud_Flag                  0
Fraud_Reason           236527
Merchant_Risk_Level         0
Merchant_Category           0
Customer_State              0
Customer_City               0
Merchant_State              0
Merchant_City               0
dtype: int64

In [4]:
print("Customers duplicates:", customers.duplicated().sum())
print("Cards duplicates:", cards.duplicated().sum())
print("Merchants duplicates:", merchants.duplicated().sum())
print("Transactions duplicates:", transactions.duplicated().sum())

Customers duplicates: 0
Cards duplicates: 0
Merchants duplicates: 0
Transactions duplicates: 0

In [5]:
print("Customers duplicates:", customers["Customer_ID"].duplicated().sum())
print("Cards duplicates:", cards["Card_ID"].duplicated().sum())
print("Merchants duplicates:", merchants["Merchant_ID"].duplicated().sum())
print("Transactions duplicates:", transactions["Transaction_ID"].duplicated().sum())

Customers duplicates: 0
Cards duplicates: 0
Merchants duplicates: 0
Transactions duplicates: 0

In [9]:
print("Customers types", customers.dtypes)
print("Cards types:", cards.dtypes)

Customers types Customer_ID           str
Customer_Name         str
Gender                str
Age                 int64
Marital_Status        str
Occupation            str
Annual_Income       int64
Customer_Segment      str
State                 str
City                  str
Account_Type          str
Customer_Since        str
dtype: object
Cards types: Card_ID           str
Customer_ID       str
Card_Type         str
Card_Network      str
Credit_Limit    int64
Card_Status       str
Contactless       str
Card_Mode         str
Issue_Date        str
Expiry_Date       str
dtype: object

In [10]:
print("Merchants types", merchants.dtypes)
print("Transactions types", transactions.dtypes)

Merchants types Merchant_ID                str
Merchant_Name              str
Merchant_Category          str
State                      str
City                       str
Merchant_Risk_Level        str
Merchant_Rating        float64
Merchant_Status            str
Merchant_Since             str
dtype: object
Transactions types Transaction_ID             str
Customer_ID                str
Card_ID                    str
Merchant_ID                str
Transaction_Date           str
Transaction_Time           str
Transaction_Amount     float64
Payment_Method             str
Transaction_Channel        str
Device_Type                str
Transaction_Status         str
Is_International         int64
Fraud_Flag               int64
Fraud_Reason               str
Merchant_Risk_Level        str
Merchant_Category          str
Customer_State             str
Customer_City              str
Merchant_State             str
Merchant_City              str
dtype: object

In [11]:
customers["Customer_Since"] = pd.to_datetime(customers["Customer_Since"])

cards["Issue_Date"] = pd.to_datetime(cards["Issue_Date"])

cards["Expiry_Date"] = pd.to_datetime(cards["Expiry_Date"])

merchants["Merchant_Since"] = pd.to_datetime(merchants["Merchant_Since"])

transactions["Transaction_Date"] = pd.to_datetime(transactions["Transaction_Date"])

In [12]:
print("Customers types", customers["Customer_Since"].dtypes)
print("Cards types:", cards["Issue_Date"].dtypes)
print("Cards types:", cards["Expiry_Date"].dtypes)
print("Merchants types", merchants["Merchant_Since"].dtypes)
print("Transactions types", transactions["Transaction_Date"].dtypes)

Customers types datetime64[us]
Cards types: datetime64[us]
Cards types: datetime64[us]
Merchants types datetime64[us]
Transactions types datetime64[us]

In [15]:
transactions["Hour"] = transactions["Transaction_Date"].dt.hour
transactions["time_period"] = pd.cut(transactions["Hour"], bins=[0, 6, 12, 18, 24], labels=["Night", "Morning", "Afternoon", "Evening"], right=False)

In [14]:
print(transactions["Transaction_Amount"].describe())

count    2.500000e+05
mean     1.660753e+04
std      5.342157e+04
min      1.000000e+02
25%      1.000000e+03
50%      3.155260e+03
75%      1.830991e+04
max      1.887057e+06
Name: Transaction_Amount, dtype: float64

In [16]:
print(transactions["Payment_Method"].value_counts())

Payment_Method
Debit Card     127789
Credit Card     88405
UPI             27678
Net Banking      6128
Name: count, dtype: int64

In [17]:
print(transactions["Transaction_Channel"].value_counts())

Transaction_Channel
POS           120284
Mobile App     64991
ATM            39902
Online Web     24823
Name: count, dtype: int64

In [18]:
print(transactions["Device_Type"].value_counts())

Device_Type
POS Terminal      120284
ATM Machine        39902
iOS Mobile         38798
Android Mobile     38587
Mac Desktop         6240
Windows PC          6189
Name: count, dtype: int64

In [19]:
print(transactions["Transaction_Status"].value_counts())

Transaction_Status
Successful    227821
Declined       12010
Failed         10169
Name: count, dtype: int64

In [20]:
print(transactions["Merchant_Category"].value_counts())

Merchant_Category
Hotel                 20946
Fashion               19525
Fuel                  19475
Travel                19434
Airline               18620
Hospital              17870
Ecommerce             17545
Financial Services    16564
Food Delivery         16458
Entertainment         16019
Pharmacy              14393
Electronics           14103
Education             13536
Grocery               12953
Utilities             12559
Name: count, dtype: int64

In [21]:
print(merchants["Merchant_Category"].value_counts())

Merchant_Category
Hotel                 42
Travel                39
Fuel                  39
Fashion               39
Airline               37
Hospital              36
Ecommerce             35
Food Delivery         33
Financial Services    33
Entertainment         32
Pharmacy              29
Electronics           28
Education             27
Grocery               26
Utilities             25
Name: count, dtype: int64

In [22]:
print(customers["Occupation"].value_counts())

Occupation
Data Analyst            2149
Lawyer                  2128
Government Employee     2124
Teacher                 2118
Farmer                  2115
Police Officer          2105
Business                2075
Nurse                   2060
Chartered Accountant    2049
Student                 2046
Software Engineer       2044
Doctor                  1987
Name: count, dtype: int64

In [23]:
print(cards["Card_Network"].value_counts)

<bound method IndexOpsMixin.value_counts of 0                   RuPay
1                    Visa
2                   RuPay
3              Mastercard
4              Mastercard
5                    Visa
6                    Visa
7              Mastercard
8              Mastercard
9                    Visa
10             Mastercard
11                   Visa
12                   Visa
13       American Express
14       American Express
15       American Express
16             Mastercard
17                  RuPay
18             Mastercard
19       American Express
20             Mastercard
21                  RuPay
22                  RuPay
23       American Express
24                  RuPay
25                   Visa
26                   Visa
27       American Express
28       American Express
29       American Express
30                  RuPay
31             Mastercard
32                   Visa
33                  RuPay
34                  RuPay
35                   Visa
36             Mastercard
37       American Express
38                  RuPay
39       American Express
40                   Visa
41       American Express
42             Mastercard
43                  RuPay
44       American Express
45                   Visa
46                   Visa
47                   Visa
48       American Express
49                  RuPay
50       American Express
51                  RuPay
52                  RuPay
53                   Visa
54             Mastercard
55       American Express
56             Mastercard
57             Mastercard
58       American Express
59             Mastercard
60       American Express
61             Mastercard
62             Mastercard
63                  RuPay
64       American Express
65             Mastercard
66                  RuPay
67             Mastercard
68                   Visa
69                  RuPay
70             Mastercard
71                  RuPay
72                  RuPay
73             Mastercard
74                  RuPay
75             Mastercard
76                   Visa
77                   Visa
78                  RuPay
79             Mastercard
80             Mastercard
81                  RuPay
82                  RuPay
83             Mastercard
84                  RuPay
85       American Express
86                  RuPay
87       American Express
88             Mastercard
89       American Express
90                   Visa
91             Mastercard
92             Mastercard
93                   Visa
94                   Visa
95                   Visa
96                   Visa
97       American Express
98                  RuPay
99                   Visa
100            Mastercard
101                  Visa
102      American Express
103      American Express
104      American Express
105                  Visa
106            Mastercard
107            Mastercard
108                  Visa
109                  Visa
110                 RuPay
111                  Visa
112                 RuPay
113                  Visa
114            Mastercard
115      American Express
116                 RuPay
117      American Express
118            Mastercard
119                 RuPay
120                  Visa
121                 RuPay
122                  Visa
123                  Visa
124            Mastercard
125            Mastercard
126      American Express
127      American Express
128                  Visa
129                 RuPay
130                 RuPay
131                 RuPay
132            Mastercard
133                 RuPay
134                  Visa
135      American Express
136            Mastercard
137                  Visa
138                  Visa
139      American Express
140                 RuPay
141      American Express
142            Mastercard
143            Mastercard
144      American Express
145            Mastercard
146                 RuPay
147      American Express
148            Mastercard
149      American Express
150                 RuPay
151            Mastercard
152                 RuPay
153      American Express
154      American Express
155            Mastercard
156      American Express
157            Mastercard
158            Mastercard
159      American Express
160                 RuPay
161                  Visa
162                  Visa
163                  Visa
164            Mastercard
165                 RuPay
166            Mastercard
167                 RuPay
168                  Visa
169                 RuPay
170                 RuPay
171                 RuPay
172                 RuPay
173                  Visa
174      American Express
175            Mastercard
176      American Express
177                  Visa
178                 RuPay
179            Mastercard
180      American Express
181            Mastercard
182                  Visa
183                 RuPay
184            Mastercard
185      American Express
186            Mastercard
187            Mastercard
188            Mastercard
189                  Visa
190            Mastercard
191      American Express
192                  Visa
193      American Express
194                  Visa
195            Mastercard
196                  Visa
197            Mastercard
198      American Express
199            Mastercard
200                  Visa
201                 RuPay
202                 RuPay
203                  Visa
204      American Express
205                 RuPay
206                 RuPay
207                  Visa
208                  Visa
209            Mastercard
210                  Visa
211                  Visa
212                 RuPay
213                 RuPay
214                  Visa
215                  Visa
216                  Visa
217                 RuPay
218                 RuPay
219            Mastercard
220      American Express
221      American Express
222                  Visa
223                  Visa
224                  Visa
225            Mastercard
226            Mastercard
227            Mastercard
228      American Express
229                 RuPay
230                 RuPay
231      American Express
232                  Visa
233            Mastercard
234            Mastercard
235      American Express
236                 RuPay
237                  Visa
238                 RuPay
239                  Visa
240      American Express
241                  Visa
242                  Visa
243      American Express
244                 RuPay
245      American Express
246                 RuPay
247                  Visa
248                 RuPay
249            Mastercard
250                 RuPay
251                 RuPay
252                  Visa
253                  Visa
254      American Express
255      American Express
256                 RuPay
257      American Express
258                  Visa
259      American Express
260                 RuPay
261            Mastercard
262      American Express
263      American Express
264                 RuPay
265                 RuPay
266            Mastercard
267      American Express
268                  Visa
269            Mastercard
270                  Visa
271            Mastercard
272                 RuPay
273                  Visa
274                 RuPay
275      American Express
276                  Visa
277                  Visa
278            Mastercard
279            Mastercard
280      American Express
281      American Express
282            Mastercard
283                  Visa
284                 RuPay
285                  Visa
286            Mastercard
287            Mastercard
288            Mastercard
289                  Visa
290                 RuPay
291                  Visa
292      American Express
293                 RuPay
294            Mastercard
295      American Express
296            Mastercard
297            Mastercard
298            Mastercard
299      American Express
300            Mastercard
301      American Express
302                  Visa
303                 RuPay
304            Mastercard
305                  Visa
306            Mastercard
307                  Visa
308            Mastercard
309                  Visa
310                 RuPay
311      American Express
312            Mastercard
313                  Visa
314                  Visa
315                 RuPay
316                 RuPay
317                 RuPay
318                  Visa
319            Mastercard
320            Mastercard
321                 RuPay
322            Mastercard
323            Mastercard
324      American Express
325                  Visa
326            Mastercard
327                  Visa
328      American Express
329      American Express
330            Mastercard
331                 RuPay
332            Mastercard
333      American Express
334                 RuPay
335      American Express
336            Mastercard
337      American Express
338                 RuPay
339                 RuPay
340                  Visa
341                  Visa
342                  Visa
343            Mastercard
344                  Visa
345                 RuPay
346      American Express
347                  Visa
348                  Visa
349            Mastercard
350      American Express
351      American Express
352                  Visa
353                 RuPay
354                 RuPay
355                  Visa
356            Mastercard
357      American Express
358      American Express
359      American Express
360            Mastercard
361      American Express
362                  Visa
363      American Express
364                  Visa
365                 RuPay
366                  Visa
367                  Visa
368            Mastercard
369                 RuPay
370                 RuPay
371                  Visa
372      American Express
373      American Express
374                 RuPay
375      American Express
376      American Express
377                  Visa
378      American Express
379                  Visa
380                  Visa
381                  Visa
382      American Express
383                  Visa
384                 RuPay
385            Mastercard
386                  Visa
387      American Express
388                 RuPay
389      American Express
390            Mastercard
391                 RuPay
392      American Express
393                  Visa
394                 RuPay
395                 RuPay
396            Mastercard
397            Mastercard
398                 RuPay
399      American Express
400      American Express
401                  Visa
402      American Express
403                 RuPay
404      American Express
405                 RuPay
406                 RuPay
407            Mastercard
408                  Visa
409                  Visa
410            Mastercard
411      American Express
412                  Visa
413                 RuPay
414      American Express
415                 RuPay
416      American Express
417      American Express
418                  Visa
419      American Express
420      American Express
421            Mastercard
422            Mastercard
423                 RuPay
424                  Visa
425                 RuPay
426                 RuPay
427      American Express
428                 RuPay
429                  Visa
430                  Visa
431            Mastercard
432                  Visa
433                  Visa
434                  Visa
435            Mastercard
436                  Visa
437            Mastercard
438                  Visa
439                  Visa
440      American Express
441      American Express
442                  Visa
443      American Express
444                  Visa
445      American Express
446      American Express
447                 RuPay
448            Mastercard
449                  Visa
450                 RuPay
451                  Visa
452            Mastercard
453                  Visa
454                 RuPay
455            Mastercard
456      American Express
457            Mastercard
458                 RuPay
459            Mastercard
460            Mastercard
461            Mastercard
462      American Express
463      American Express
464                 RuPay
465                 RuPay
466      American Express
467            Mastercard
468            Mastercard
469            Mastercard
470            Mastercard
471                 RuPay
472                 RuPay
473                 RuPay
474                 RuPay
475                 RuPay
476                 RuPay
477            Mastercard
478                 RuPay
479                  Visa
480                  Visa
481            Mastercard
482                  Visa
483                  Visa
484                 RuPay
485                 RuPay
486      American Express
487            Mastercard
488            Mastercard
489                  Visa
490      American Express
491            Mastercard
492                 RuPay
493      American Express
494                  Visa
495                 RuPay
496                  Visa
497                 RuPay
498            Mastercard
499                  Visa
500            Mastercard
501      American Express
502      American Express
503                 RuPay
504            Mastercard
505      American Express
506      American Express
507                  Visa
508      American Express
509      American Express
510                  Visa
511            Mastercard
512      American Express
513      American Express
514      American Express
515      American Express
516                  Visa
517            Mastercard
518                 RuPay
519            Mastercard
520                  Visa
521                  Visa
522                 RuPay
523            Mastercard
524                 RuPay
525                  Visa
526      American Express
527                 RuPay
528                  Visa
529      American Express
530            Mastercard
531      American Express
532      American Express
533            Mastercard
534                 RuPay
535                 RuPay
536                  Visa
537      American Express
538                  Visa
539                  Visa
540      American Express
541                  Visa
542                 RuPay
543      American Express
544                  Visa
545            Mastercard
546            Mastercard
547                 RuPay
548      American Express
549                  Visa
550                  Visa
551                  Visa
552                  Visa
553                 RuPay
554                 RuPay
555      American Express
556                  Visa
557                 RuPay
558                 RuPay
559                 RuPay
560                  Visa
561                 RuPay
562                 RuPay
563            Mastercard
564                  Visa
565                  Visa
566                  Visa
567                 RuPay
568                  Visa
569                  Visa
570            Mastercard
571                  Visa
572            Mastercard
573      American Express
574                  Visa
575                  Visa
576                  Visa
577      American Express
578                  Visa
579      American Express
580                 RuPay
581                  Visa
582            Mastercard
583                 RuPay
584                  Visa
585                  Visa
586                 RuPay
587      American Express
588      American Express
589                 RuPay
590      American Express
591                 RuPay
592                  Visa
593                 RuPay
594            Mastercard
595      American Express
596                  Visa
597                 RuPay
598                  Visa
599                  Visa
600                 RuPay
601            Mastercard
602                  Visa
603      American Express
604                  Visa
605            Mastercard
606            Mastercard
607                  Visa
608                 RuPay
609                 RuPay
610                 RuPay
611      American Express
612                 RuPay
613                  Visa
614      American Express
615                  Visa
616                 RuPay
617                  Visa
618                  Visa
619            Mastercard
620                 RuPay
621      American Express
622                  Visa
623      American Express
624                  Visa
625      American Express
626      American Express
627                 RuPay
628            Mastercard
629                  Visa
630      American Express
631                 RuPay
632                  Visa
633      American Express
634            Mastercard
635      American Express
636      American Express
637            Mastercard
638            Mastercard
639            Mastercard
640            Mastercard
641                  Visa
642                  Visa
643            Mastercard
644      American Express
645            Mastercard
646                 RuPay
647            Mastercard
648                 RuPay
649            Mastercard
650                 RuPay
651            Mastercard
652                  Visa
653                 RuPay
654                 RuPay
655            Mastercard
656                 RuPay
657                 RuPay
658            Mastercard
659                  Visa
660      American Express
661      American Express
662                  Visa
663            Mastercard
664            Mastercard
665                  Visa
666            Mastercard
667                  Visa
668            Mastercard
669                 RuPay
670                  Visa
671            Mastercard
672            Mastercard
673                 RuPay
674                 RuPay
675                  Visa
676                 RuPay
677      American Express
678      American Express
679                  Visa
680      American Express
681                 RuPay
682                 RuPay
683                  Visa
684                  Visa
685            Mastercard
686      American Express
687                  Visa
688            Mastercard
689      American Express
690      American Express
691            Mastercard
692            Mastercard
693                  Visa
694                  Visa
695                  Visa
696                  Visa
697            Mastercard
698                 RuPay
699            Mastercard
700                 RuPay
701            Mastercard
702      American Express
703                  Visa
704            Mastercard
705                  Visa
706      American Express
707            Mastercard
708      American Express
709            Mastercard
710            Mastercard
711            Mastercard
712                  Visa
713                 RuPay
714                 RuPay
715            Mastercard
716                  Visa
717                 RuPay
718                 RuPay
719                  Visa
720                  Visa
721      American Express
722                 RuPay
723      American Express
724            Mastercard
725      American Express
726            Mastercard
727      American Express
728                  Visa
729                  Visa
730                  Visa
731                  Visa
732      American Express
733                  Visa
734            Mastercard
735                 RuPay
736                  Visa
737                 RuPay
738            Mastercard
739      American Express
740      American Express
741            Mastercard
742                  Visa
743                  Visa
744            Mastercard
745                  Visa
746            Mastercard
747                  Visa
748      American Express
749                 RuPay
750                 RuPay
751            Mastercard
752            Mastercard
753            Mastercard
754                  Visa
755                 RuPay
756      American Express
757            Mastercard
758      American Express
759                  Visa
760                  Visa
761                  Visa
762                 RuPay
763                  Visa
764                  Visa
765      American Express
766            Mastercard

In [25]:
customers["Marital_Status"] = customers["Marital_Status"].replace({"Divorsed": "Divorced"})
print(customers["Marital_Status"])

0          Single
1         Married
2        Divorced
3          Single
4          Single
5         Married
6         Married
7         Married
8         Married
9         Married
10        Married
11        Married
12       Divorced
13        Married
14        Married
15         Single
16        Married
17        Married
18         Single
19        Married
20        Married
21        Married
22        Married
23        Married
24        Married
25        Married
26       Divorced
27        Married
28        Married
29        Married
30         Single
31        Married
32        Married
33        Married
34         Single
35        Married
36        Married
37        Married
38        Married
39        Married
40       Divorced
41         Single
42        Married
43        Married
44        Married
45        Married
46         Single
47        Married
48        Married
49       Divorced
50       Divorced
51         Single
52        Married
53        Married
54         Single
55        Married
56        Married
57         Single
58        Married
59        Married
60        Married
61        Married
62       Divorced
63        Married
64        Married
65        Married
66         Single
67        Married
68         Single
69        Married
70       Divorced
71        Married
72        Married
73        Married
74        Married
75        Married
76        Married
77       Divorced
78        Married
79        Married
80        Married
81        Married
82        Married
83        Married
84        Married
85        Married
86        Married
87        Married
88        Married
89         Single
90        Married
91        Married
92        Married
93         Single
94         Single
95        Married
96        Married
97         Single
98        Married
99        Married
100       Married
101       Married
102       Married
103       Married
104       Married
105       Married
106        Single
107       Married
108       Married
109        Single
110       Married
111       Married
112       Married
113       Married
114       Married
115        Single
116       Married
117       Married
118       Married
119       Married
120       Married
121      Divorced
122       Married
123       Married
124        Single
125       Married
126        Single
127       Married
128       Married
129       Married
130       Married
131      Divorced
132       Married
133       Married
134       Married
135       Married
136       Married
137       Married
138       Married
139       Married
140       Married
141      Divorced
142       Married
143       Married
144        Single
145      Divorced
146       Married
147       Married
148       Married
149       Married
150      Divorced
151       Married
152      Divorced
153      Divorced
154       Married
155        Single
156       Married
157      Divorced
158        Single
159       Married
160        Single
161       Married
162       Married
163       Married
164       Married
165       Married
166       Married
167       Married
168        Single
169        Single
170       Married
171        Single
172       Married
173       Married
174       Married
175       Married
176       Married
177        Single
178       Married
179       Married
180       Married
181       Married
182       Married
183      Divorced
184       Married
185       Married
186        Single
187       Married
188       Married
189       Married
190       Married
191       Married
192       Married
193       Married
194       Married
195       Married
196      Divorced
197       Married
198       Married
199        Single
200       Married
201        Single
202       Married
203      Divorced
204       Married
205       Married
206       Married
207       Married
208       Married
209       Married
210       Married
211       Married
212       Married
213       Married
214        Single
215       Married
216       Married
217        Single
218       Married
219      Divorced
220      Divorced
221       Married
222        Single
223       Married
224       Married
225       Married
226       Married
227       Married
228        Single
229       Married
230       Married
231        Single
232       Married
233       Married
234       Married
235       Married
236       Married
237       Married
238       Married
239       Married
240      Divorced
241       Married
242       Married
243        Single
244       Married
245       Married
246       Married
247        Single
248       Married
249      Divorced
250       Married
251       Married
252        Single
253       Married
254       Married
255        Single
256       Married
257       Married
258       Married
259        Single
260        Single
261       Married
262       Married
263       Married
264      Divorced
265       Married
266       Married
267        Single
268      Divorced
269       Married
270       Married
271       Married
272      Divorced
273       Married
274       Married
275        Single
276       Married
277       Married
278       Married
279       Married
280       Married
281        Single
282      Divorced
283        Single
284       Married
285       Married
286       Married
287      Divorced
288       Married
289       Married
290       Married
291       Married
292       Married
293       Married
294       Married
295        Single
296       Married
297       Married
298       Married
299        Single
300       Married
301        Single
302       Married
303        Single
304       Married
305       Married
306       Married
307       Married
308       Married
309      Divorced
310        Single
311        Single
312       Married
313       Married
314        Single
315       Married
316       Married
317        Single
318       Married
319       Married
320        Single
321        Single
322       Married
323       Married
324      Divorced
325        Single
326      Divorced
327       Married
328       Married
329       Married
330       Married
331        Single
332       Married
333       Married
334       Married
335       Married
336       Married
337        Single
338       Married
339      Divorced
340      Divorced
341       Married
342       Married
343       Married
344       Married
345       Married
346       Married
347       Married
348        Single
349       Married
350        Single
351       Married
352       Married
353       Married
354      Divorced
355        Single
356       Married
357       Married
358       Married
359       Married
360       Married
361       Married
362       Married
363       Married
364       Married
365       Married
366       Married
367       Married
368       Married
369      Divorced
370       Married
371      Divorced
372       Married
373       Married
374       Married
375      Divorced
376       Married
377        Single
378       Married
379       Married
380        Single
381       Married
382       Married
383        Single
384       Married
385       Married
386       Married
387       Married
388        Single
389       Married
390       Married
391        Single
392       Married
393       Married
394       Married
395       Married
396       Married
397       Married
398       Married
399       Married
400       Married
401      Divorced
402      Divorced
403        Single
404       Married
405       Married
406       Married
407       Married
408       Married
409        Single
410       Married
411       Married
412       Married
413       Married
414      Divorced
415        Single
416        Single
417       Married
418      Divorced
419        Single
420       Married
421       Married
422      Divorced
423       Married
424       Married
425       Married
426       Married
427       Married
428       Married
429       Married
430      Divorced
431      Divorced
432       Married
433       Married
434       Married
435       Married
436       Married
437        Single
438       Married
439       Married
440        Single
441       Married
442        Single
443       Married
444      Divorced
445       Married
446      Divorced
447       Married
448       Married
449       Married
450       Married
451       Married
452        Single
453       Married
454       Married
455       Married
456        Single
457       Married
458        Single
459       Married
460       Married
461       Married
462       Married
463       Married
464        Single
465       Married
466       Married
467       Married
468      Divorced
469       Married
470       Married
471       Married
472       Married
473        Single
474       Married
475      Divorced
476       Married
477       Married
478       Married
479       Married
480      Divorced
481       Married
482       Married
483       Married
484       Married
485       Married
486       Married
487       Married
488       Married
489       Married
490       Married
491        Single
492        Single
493       Married
494       Married
495       Married
496       Married
497        Single
498       Married
499       Married
500        Single
501       Married
502       Married
503        Single
504        Single
505       Married
506       Married
507       Married
508        Single
509       Married
510        Single
511       Married
512       Married
513       Married
514       Married
515      Divorced
516       Married
517       Married
518      Divorced
519       Married
520       Married
521       Married
522       Married
523        Single
524       Married
525       Married
526       Married
527        Single
528       Married
529      Divorced
530       Married
531       Married
532       Married
533       Married
534       Married
535      Divorced
536       Married
537       Married
538       Married
539       Married
540       Married
541       Married
542       Married
543       Married
544       Married
545       Married
546       Married
547       Married
548      Divorced
549      Divorced
550        Single
551       Married
552       Married
553        Single
554       Married
555       Married
556       Married
557        Single
558       Married
559        Single
560       Married
561       Married
562       Married
563       Married
564       Married
565       Married
566        Single
567       Married
568      Divorced
569       Married
570       Married
571        Single
572       Married
573       Married
574        Single
575       Married
576       Married
577       Married
578      Divorced
579       Married
580       Married
581       Married
582       Married
583        Single
584       Married
585       Married
586      Divorced
587        Single
588       Married
589       Married
590       Married
591       Married
592        Single
593       Married
594        Single
595       Married
596      Divorced
597       Married
598        Single
599       Married
600      Divorced
601       Married
602       Married
603       Married
604       Married
605       Married
606       Married
607      Divorced
608       Married
609      Divorced
610       Married
611       Married
612       Married
613        Single
614        Single
615       Married
616      Divorced
617        Single
618       Married
619       Married
620       Married
621       Married
622       Married
623        Single
624      Divorced
625       Married
626       Married
627       Married
628        Single
629        Single
630       Married
631       Married
632        Single
633       Married
634       Married
635       Married
636       Married
637       Married
638       Married
639       Married
640       Married
641       Married
642       Married
643       Married
644       Married
645       Married
646       Married
647       Married
648       Married
649      Divorced
650       Married
651       Married
652       Married
653       Married
654        Single
655       Married
656        Single
657      Divorced
658      Divorced
659        Single
660       Married
661       Married
662       Married
663       Married
664       Married
665       Married
666        Single
667       Married
668       Married
669       Married
670       Married
671       Married
672        Single
673        Single
674       Married
675       Married
676       Married
677       Married
678       Married
679      Divorced
680       Married
681        Single
682       Married
683       Married
684        Single
685       Married
686       Married
687       Married
688       Married
689       Married
690        Single
691        Single
692        Single
693       Married
694       Married
695       Married
696       Married
697       Married
698       Married
699       Married
700       Married
701       Married
702      Divorced
703       Married
704       Married
705        Single
706       Married
707       Married
708       Married
709       Married
710       Married
711       Married
712       Married
713      Divorced
714       Married
715       Married
716       Married
717       Married
718       Married
719       Married
720        Single
721      Divorced
722       Married
723       Married
724       Married
725       Married
726       Married
727        Single
728        Single
729       Married
730        Single
731        Single
732       Married
733       Married
734       Married
735        Single
736       Married
737       Married
738       Married
739       Married
740        Single
741       Married
742        Single
743       Married
744       Married
745       Married
746       Married
747       Married
748        Single
749        Single
750       Married
751       Married
752       Married
753       Married
754       Married
755        Single
756        Single
757       Married
758        Single
759       Married
760       Married
761       Married
762       Married
763       Married
764       Married
765      Divorced
766       Married
767       Married
768       Married
769       Married
770       Married
771       Married
772      Divorced
773       Married
774        Single
775      Divorced
776       Married
777        Single
778       Married
779       Married
780       Married
781       Married
782       Married
783        Single
784        Single
785       Married
786        Single
787       Married
788        Single
789       Married
790        Single
791       Married
792      Divorced
793        Single
794       Married
795       Married
796       Married
797       Married
798       Married
799       Married
800        Single
801      Divorced
802       Married
803       Married
804       Married
805      Divorced
806       Married
807        Single
808       Married
809       Married
810        Single
811       Married
812       Married
813       Married
814       Married
815       Married
816       Married
817       Married
818        Single
819        Single
820        Single
821        Single
822       Married
823       Married
824       Married
825       Married
826       Married
827        Single
828       Married
829       Married
830       Married
831       Married
832       Married
833       Married
834       Married
835       Married
836       Married
837       Married
838       Married
839       Married
840       Married
841       Married
842        Single
843        Single
844       Married
845       Married
846       Married
847       Married
848        Single
849       Married
850      Divorced
851       Married
852       Married
853        Single
854       Married
855       Married
856       Married
857       Married
858      Divorced
859       Married
860       Married
861       Married
862       Married
863       Married
864       Married
865        Single
866      Divorced
867        Single
868       Married
869       Married
870       Married
871       Married
872       Married
873       Married
874       Married
875       Married
876       Married
877       Married
878       Married
879       Married
880       Married
881       Married
882       Married
883       Married
884      Divorced
885        Single
886        Single
887       Married
888       Married
889       Married
890       Married
891       Married
892        Single
893       Married
894       Married
895       Married
896      Divorced
897       Married
898        Single
899       Married
900      Divorced
901       Married
902      Divorced
903      Divorced
904       Married
905       Married
906       Married
907       Married
908      Divorced
909       Married
910       Married
911       Married
912       Married
913       Married
914        Single
915       Married
916       Married
917       Married
918      Divorced
919       Married
920       Married
921        Single
922       Married
923       Married
924       Married
925        Single
926        Single
927       Married
928        Single
929        Single
930       Married
931       Married
932       Married
933       Married
934       Married
935       Married
936       Married
937       Married
938       Married
939       Married
940      Divorced
941       Married
942        Single
943       Married
944       Married
945       Married
946       Married
947       Married
948       Married
949       Married
950       Married
951       Married
952        Single
953       Married
954       Married
955        Single
956       Married
957       Married
958       Married
959       Married
960       Married
961       Married
962       Married
963       Married
964       Married
965        Single
966       Married
967       Married
968       Married
969        Single
970       Married
971       Married
972       Married
973      Divorced
974       Married
975       Married
976        Single
977      Divorced
978       Married
979       Married
980       Married
981       Married
982        Single
983       Married
984      Divorced
985       Married
986       Married
987       Married
988       Married
989        Single
990       Married
991       Married
992       Married
993       Married
994       Married
995       Married
996       Married
997       Married
998       Married
999       Married
1000       Single
1001      Married
1002      Married
1003     Divorced
1004      Married
1005      Married
1006       Single
1007     Divorced
1008      Married
1009      Married
1010      Married
1011       Single
1012       Single
1013      Married
1014       Single
1015      Married
1016      Married
1017      Married
1018      Married
1019       Single
1020       Single
1021       Single
1022      Married
1023      Married
1024      Married
1025     Divorced
1026      Married
1027     Divorced
1028       Single
1029       Single
1030       Single
1031       Single
1032     Divorced
1033       Single
1034      Married
1035     Divorced
1036      Married
1037      Married
1038       Single
1039      Married
1040       Single
1041       Single
1042       Single
1043       Single
1044      Married
1045      Married
1046      Married
1047      Married
1048     Divorced
1049      Married
1050      Married
1051      Married
1052       Single
1053      Married
1054      Married
1055       Single
1056      Married
1057      Married
1058       Single
1059      Married
1060       Single
1061       Single
1062      Married
1063      Married
1064     Divorced
1065      Married
1066      Married
1067      Married
1068       Single
1069      Married
1070      Married
1071      Married
1072      Married
1073      Married
1074       Single
1075       Single
1076      Married
1077      Married
1078      Married
1079      Married
1080      Married
1081      Married
1082       Single
1083      Married
1084      Married
1085      Married
1086      Married
1087      Married
1088      Married
1089      Married
1090      Married
1091      Married
1092      Married
1093      Married
1094       Single
1095      Married
1096       Single
1097      Married
1098       Single
1099      Married
1100       Single
1101      Married
1102      Married
1103       Single
1104       Single
1105      Married
1106      Married
1107     Divorced
1108      Married
1109     Divorced
1110     Divorced

In [ ]:
print(cards["Customer_ID"].isin(customers["Customer_ID"])) #check whether each Customer_ID in cards exists in customers:

0        True
1        True
2        True
3        True
4        True
         ...
32452    True
32453    True
32454    True
32455    True
32456    True
Name: Customer_ID, Length: 32457, dtype: bool

In [ ]:
print(transactions["Customer_ID"].isin(customers["Customer_ID"])) #check whether each Customer_ID in transactions exists in customers:

0         True
1         True
2         True
3         True
4         True
          ...
249995    True
249996    True
249997    True
249998    True
249999    True
Name: Customer_ID, Length: 250000, dtype: bool

In [ ]:
print(transactions["Card_ID"].isin(cards["Card_ID"])) #check whether each Card_ID in transactions exists in cards:

0         True
1         True
2         True
3         True
4         True
          ...
249995    True
249996    True
249997    True
249998    True
249999    True
Name: Card_ID, Length: 250000, dtype: bool

In [ ]:
print(transactions["Merchant_ID"].isin(merchants["Merchant_ID"])) #check whether each Merchant_ID in transactions exists in merchants:

0         True
1         True
2         True
3         True
4         True
          ...
249995    True
249996    True
249997    True
249998    True
249999    True
Name: Merchant_ID, Length: 250000, dtype: bool

In [ ]:
master = transactions.merge(customers,on="Customer_ID",how="left",suffixes=("", "_Customer")) # Merge transactions with customers

In [ ]:
master = master.merge(cards,on=["Card_ID", "Customer_ID"],how="left",suffixes=("", "_Card")) # Merge the resulting DataFrame with cards on Card_ID and Customer_ID

In [ ]:
master = master.merge(merchants,on="Merchant_ID",how="left",suffixes=("", "_Merchant")) # Merge the resulting DataFrame with merchants on Merchant_ID

In [ ]:
print(master.shape)  # Print the shape of the merged DataFrame
print(master.head())  # Print the first 5 rows of the merged DataFrame

(250000, 55)
  Transaction_ID Customer_ID     Card_ID Merchant_ID Transaction_Date  \
0     TXN1000001  CUST100660  CARD500875   MER100380       2024-03-03
1     TXN1000002  CUST111388  CARD514772   MER100017       2023-11-08
2     TXN1000003  CUST115872  CARD520625   MER100143       2023-01-11
3     TXN1000004  CUST109049  CARD511773   MER100053       2023-05-25
4     TXN1000005  CUST114459  CARD518771   MER100064       2023-10-22

  Transaction_Time  Transaction_Amount Payment_Method Transaction_Channel  \
0         05:50:10            21748.02     Debit Card          Mobile App
1         06:55:15             9960.60     Debit Card                 POS
2         02:17:28              838.61     Debit Card                 ATM
3         01:48:56            52694.99    Credit Card                 POS
4         00:23:32             1043.40     Debit Card          Online Web

      Device_Type  ... Issue_Date_Card  Expiry_Date_Card  Merchant_Name  \
0  Android Mobile  ...      2021-09-07        2026-09-07     Taj Hotels
1    POS Terminal  ...      2023-09-23        2028-09-23         Redbus
2     ATM Machine  ...      2020-08-22        2025-08-22      Pizza Hut
3    POS Terminal  ...      2020-10-31        2025-10-31        PhonePe
4  Android Mobile  ...      2019-07-16        2024-07-16  Netflix India

  Merchant_Category_Merchant  State_Merchant City_Merchant  \
0                      Hotel      Tamil Nadu         Salem
1                     Travel         Haryana           Nuh
2              Food Delivery     West Bengal       Kolkata
3         Financial Services  Madhya Pradesh        Indore
4              Entertainment  Madhya Pradesh      Jabalpur

  Merchant_Risk_Level_Merchant Merchant_Rating Merchant_Status Merchant_Since
0                          Low             4.3          Active     2021-04-20
1                          Low             4.1          Active     2022-03-03
2                          Low             4.0          Active     2019-06-11
3                          Low             4.4          Active     2011-06-25
4                          Low             4.9          Active     2011-04-02

[5 rows x 55 columns]

In [ ]:
print(master["Transaction_ID"].duplicated().sum()) # Print the number of duplicate Transaction_ID values

0

In [ ]:
print(master.shape) # Print the shape of the merged DataFrame

(250000, 55)

In [ ]:
master["Fraud_Amount"] = np.where(master["Fraud_Flag"] == 1,master["Transaction_Amount"],0) # Create a new column for fraud amount

In [ ]:
master["Successful_Flag"] = np.where(master["Transaction_Status"] == "Successful",1,0) # Create a new column for successful transactions

In [20]:
master["Declined_Flag"] = np.where(master["Transaction_Status"] == "Declined",1,0) # Create a new column for declined transactions

In [21]:
fraud_count = master["Fraud_Flag"].sum() # Calculate the total number of fraudulent transactions

print(fraud_count) # Print the total number of fraudulent transactions

13473

In [ ]:
fraud_rate = (master["Fraud_Flag"].mean()*100) # Calculate the fraud rate as a percentage of total transactions
print(round(fraud_rate, 2), "%") # Print the fraud rate as a percentage

5.39 %

In [26]:
fraud_payment = pd.crosstab(master["Payment_Method"],master["Fraud_Flag"],normalize="index") * 100
print(fraud_payment.round(2))

Fraud_Flag          0     1
Payment_Method
Credit Card     94.50  5.50
Debit Card      94.68  5.32
Net Banking     94.58  5.42
UPI             94.67  5.33

In [ ]:
fraud_category = master.groupby("Merchant_Category").agg(Transactions=("Transaction_ID", "count"),Fraud_Count=("Fraud_Flag", "sum"),Transaction_Amount=("Transaction_Amount", "sum")) # Group by merchant category and calculate transaction metrics
fraud_category["Fraud_Rate"] = (fraud_category["Fraud_Count"]/ fraud_category["Transactions"]* 100) # Calculate fraud rate as a percentage
print(fraud_category.sort_values("Fraud_Rate",ascending=False)) # Print the sorted fraud category data

                    Transactions  Fraud_Count  Transaction_Amount  Fraud_Rate
Merchant_Category
Entertainment              16019          906        7.898618e+07    5.655784
Utilities                  12559          705        5.908871e+07    5.613504
Travel                     19434         1062        3.466941e+08    5.464650
Hotel                      20946         1143        4.140396e+08    5.456889
Fuel                       19475         1062        9.898916e+07    5.453145
Hospital                   17870          973        6.247056e+08    5.444880
Ecommerce                  17545          953        1.628800e+08    5.431747
Food Delivery              16458          890        5.361370e+07    5.407704
Grocery                    12953          699        7.179562e+07    5.396433
Electronics                14103          754        5.223277e+08    5.346380
Airline                    18620          992        6.083301e+08    5.327605
Pharmacy                   14393          766        6.425935e+07    5.322032
Financial Services         16564          873        3.943191e+08    5.270466
Fashion                    19525         1014        1.761694e+08    5.193342
Education                  13536          681        4.756831e+08    5.031028

In [31]:
fraud_segment = master.groupby("Customer_Segment").agg(Transactions=("Transaction_ID", "count"),Fraud_Count=("Fraud_Flag", "sum"),Amount=("Transaction_Amount", "sum")) # Group by customer segment and calculate transaction metrics
fraud_segment["Fraud_Rate"] = (fraud_segment["Fraud_Count"]/ fraud_segment["Transactions"] * 100) # Calculate fraud rate as a percentage
print(fraud_segment) # Print the fraud segment data

                  Transactions  Fraud_Count        Amount  Fraud_Rate
Customer_Segment
Basic                    23698         1284  3.554912e+08    5.418179
Gold                     80428         4279  1.299591e+09    5.320286
Platinum                 83269         4547  1.542090e+09    5.460616
Standard                 62605         3363  9.547085e+08    5.371775

In [32]:
fraud_state = master.groupby("Customer_State").agg(Transactions=("Transaction_ID", "count"),Fraud_Count=("Fraud_Flag", "sum"),Amount=("Transaction_Amount", "sum")) # Group by customer state and calculate transaction metrics
fraud_state["Fraud_Rate"] = (fraud_state["Fraud_Count"]/ fraud_state["Transactions"] * 100) # Calculate fraud rate as a percentage
print(fraud_state.sort_values("Fraud_Rate",ascending=False)) # Print the sorted fraud state data

                Transactions  Fraud_Count        Amount  Fraud_Rate
Customer_State
Uttar Pradesh          17077         1016  2.808630e+08    5.949523
Telangana              16866          972  2.778584e+08    5.763074
Gujarat                16510          946  2.745081e+08    5.729861
Haryana                16556          921  2.781602e+08    5.562938
Odisha                 16572          916  2.810821e+08    5.527396
Bihar                  16458          898  2.678000e+08    5.456313
Kerala                 17358          933  3.027842e+08    5.375043
Punjab                 16547          882  2.779904e+08    5.330271
Assam                  16354          869  2.776132e+08    5.313685
Madhya Pradesh         16243          854  2.692257e+08    5.257649
Karnataka              17275          907  2.808002e+08    5.250362
West Bengal            16960          886  2.800600e+08    5.224057
Rajasthan              16553          864  2.752738e+08    5.219598
Maharashtra            16319          834  2.643189e+08    5.110607
Tamil Nadu             16352          775  2.635431e+08    4.739481

In [33]:
international = master.groupby("Is_International").agg(Transactions=("Transaction_ID", "count"),Fraud_Count=("Fraud_Flag", "sum"),Amount=("Transaction_Amount", "sum")) # Group by international transactions and calculate transaction metrics
international["Fraud_Rate"] = ( international["Fraud_Count"]/ international["Transactions"] * 100) # Calculate fraud rate as a percentage
print(international)  # Print the international transaction data

                  Transactions  Fraud_Count        Amount  Fraud_Rate
Is_International
0                       237428        10997  3.653304e+09    4.631720
1                        12572         2476  4.985777e+08   19.694559

In [34]:
#Fraud by card type

card_analysis = master.groupby("Card_Type").agg(Transactions=("Transaction_ID", "count"),Fraud_Count=("Fraud_Flag", "sum"),Amount=("Transaction_Amount", "sum")) # Group by card type and calculate transaction metrics
card_analysis["Fraud_Rate"] = (card_analysis["Fraud_Count"]/ card_analysis["Transactions"] * 100) # Calculate fraud rate as a percentage
print(card_analysis) # Print the card type analysis data

           Transactions  Fraud_Count        Amount  Fraud_Rate
Card_Type
Classic           56998         3065  8.126635e+08    5.377382
Gold              76927         4145  1.307181e+09    5.388225
Platinum          46415         2587  9.774957e+08    5.573629
Silver            69660         3676  1.054541e+09    5.277060

In [35]:
#Fraud by card status

card_status_analysis = master.groupby("Card_Status").agg(Transactions=("Transaction_ID", "count"),Fraud_Count=("Fraud_Flag", "sum")) # Group by card status and calculate transaction metrics
card_status_analysis["Fraud_Rate"] = (card_status_analysis["Fraud_Count"]/ card_status_analysis["Transactions"] * 100) # Calculate fraud rate as a percentage
print(card_status_analysis) # Print the card status analysis data

             Transactions  Fraud_Count  Fraud_Rate
Card_Status
Active             245091         8564    3.494212
Blocked              1591         1591  100.000000
Expired              2470         2470  100.000000
Lost                  848          848  100.000000

In [38]:
fraud_reasons = (master[master["Fraud_Flag"] == 1]["Fraud_Reason"].value_counts()) 

print(fraud_reasons)

Fraud_Reason
Transaction Attempt on Expired Card                 2470
High Risk Merchant Category Spike                   1758
Unusual Cross-Border / International Transaction    1721
Unusual High Transaction Amount vs Credit Limit     1707
Rapid Velocity & Multiple Failed Auth Attempts      1702
Late Night Geographical & Velocity Anomaly          1676
Transaction Attempt on Blocked Card                 1591
Transaction Attempt on Lost Card                     848
Name: count, dtype: int64

In [39]:
master.to_csv("banking_master_cleaned.csv",index=False)

In [41]:
fraud_category.to_csv("fraud_by_category.csv")

fraud_segment.to_csv("fraud_by_segment.csv")

fraud_state.to_csv("fraud_by_state.csv")